// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsrQPXBxziF8weBC91CEQuhc8lb01EqJM',
    appId: '1:1076289879683:web:d8d4536e4d5e741aa565b6',
    messagingSenderId: '1076289879683',
    projectId: 'mechanicapp-a10ab',
    authDomain: 'mechanicapp-a10ab.firebaseapp.com',
    storageBucket: 'mechanicapp-a10ab.appspot.com',
    measurementId: 'G-R0ZD9KV8J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYVxZ4BNxe-ZGCvjlJODqvLS-bnIgMI4M',
    appId: '1:1076289879683:android:a74aada7ed860a88a565b6',
    messagingSenderId: '1076289879683',
    projectId: 'mechanicapp-a10ab',
    storageBucket: 'mechanicapp-a10ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGenqF3dji03pxrVjMafWjv4pfBI5ufdc',
    appId: '1:1076289879683:ios:4e175d4b5a9b0700a565b6',
    messagingSenderId: '1076289879683',
    projectId: 'mechanicapp-a10ab',
    storageBucket: 'mechanicapp-a10ab.appspot.com',
    iosBundleId: 'com.example.mechanicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGenqF3dji03pxrVjMafWjv4pfBI5ufdc',
    appId: '1:1076289879683:ios:4e175d4b5a9b0700a565b6',
    messagingSenderId: '1076289879683',
    projectId: 'mechanicapp-a10ab',
    storageBucket: 'mechanicapp-a10ab.appspot.com',
    iosBundleId: 'com.example.mechanicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsrQPXBxziF8weBC91CEQuhc8lb01EqJM',
    appId: '1:1076289879683:web:7531dd23933ff077a565b6',
    messagingSenderId: '1076289879683',
    projectId: 'mechanicapp-a10ab',
    authDomain: 'mechanicapp-a10ab.firebaseapp.com',
    storageBucket: 'mechanicapp-a10ab.appspot.com',
    measurementId: 'G-NWZJCTRY54',
  );
}
